config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  resources :pins
	get "/comments" => 'comments#index'
	post "/comments" => 'comments#create'

  devise_for :users
  root "pins#index" # root_path
  get "about" => "pages#about" # about_path

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :user

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  validates :image, presence: true
  validates :description, presence: true
  validates :shape, presence: true
  validates :length, presence: true
  validates :ring, presence: true
  validates :wrapper, presence: true

  ratyrate_rateable 'construction', 'burn', 'flavor', 'overall'
	
	def self.cigar_shape
		return ["Corona","Petit Corona","Churchill","Robusto","Corona Gorda",
						"Double Corona","Panetela","Lonsdale","Pyramid","Belicoso",
						"Torpedo","Perfecto","Culebra","Diadem","Presidente","Chisel",
						"Parejo","Petit Robusto","Gorda","Toro","Corona Grande",
						"Lonsdale","Lancero","Gran Corona","Nub"].sort
	end
	def self.cigar_wrapper
		return ["Connecticut","Corojo","Habano","Maduro",
						"Candela","Sumatra","Oscuro","Cameroon",
						"Grown","Criollo","Colorado","San Andres",
						"Natural","Rosado","Sun Grown","Other"].sort
	end
	def self.cigar_length
		return ["3","3.5","4","4.5","5","5.5","6","6.5","7","7.5","8","8.5","9"]	
	end
	def self.cigar_ring
		return ["20","21","22","23","24","25","26","27","28","29",
						"30","31","32","33","34","35","36","37","38","39",
						"40","41","42","43","44","45","46","47","48","49",
						"50","51","52","53","54","55","56","57","58","59",
						"60","61","62","63","64","65","66","67","68","69",
						"70","71","72","73","74","75","76","77","78","79"]
	end
  
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins

  validates :name, presence: true

  ratyrate_rater
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  helper :all

  protected 

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def index
		@comments = get_pin_comments 
		render :json => { comments: @comments }
	end

	def create
		Comment.create(pin_id: params[:pin_id], user_id: current_user.id, comment: params[:body])
		render :json => { comments: @comments }
	end

	private 
		# return array of comment objects for the given pin
		def get_pin_comments
			allC = []
			Comment.all.each do |c|
				if c.pin_id == params[:pin_id].to_i 
					cO = {
						user: User.find(c.user_id).name,
						body: c.comment
					}
      	allC << cO
				end
      end
			allC
		end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  respond_to :html

  def index
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 8)
    respond_with(@pins)
  end

  def show
    respond_with(@pins)
  end

  def new
    @pin = current_user.pins.build 
    respond_with(@pin)
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    @pin.save
    respond_with(@pin)
  end

  def update
    @pin.update(pin_params)
    respond_with(@pin)
  end

  def destroy
    @pin.destroy
    respond_with(@pin)
  end

  private
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      if user_signed_in? 
        @pin = current_user.pins.find_by(id: params[:id])
        redirect_to pins_path, notice: "You are not authorized to edit this pin" if @pin.nil?
      else
        redirect_to pins_path, notice: "You must be signed in to edit pins"
      end
    end	

    def pin_params
      params.require(:pin).permit(:description, :image, :shape, :length, :ring, :wrapper)
    end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/rater_helper.rb
module RaterHelper
  def overall 
    sum = 0
    count = 0
    get_rates.each do |rate|
      if rate.dimension != "overall"
        sum += rate.stars
        count += 1
      end
    end
    return find_avg_rate(sum, count) 
  end

  def get_rates
    @rates = []
    Rate.all.each do |rate|
      if @pin.id == rate.rateable_id
        @rates << rate
      end 
    end
    return @rates
  end

  def find_avg_rate(sum, count)
    if count == 0
      return 0
    else
      init_avg = sum / count
      mod_avg = (sum - (sum % count)) / count
      if (init_avg - mod_avg) >= 0.5
        return mod_avg + 1
      else
        return mod_avg
      end 
    end
  end
end

app/views/comments/_index.html.erb
<div class="panel panel-main"  ng-app='commentsNg' ng-controller='CommentsCtrl'>
	<span ng-init="pin_id = '<%= @pin.id %>'"></span>
  <div class="comment" ng-repeat='comment in comments'>
    <div class="comment-user">{{comment.user}}</div>
    <br>
    {{comment.body}}
  </div>
  <form ng-submit="addComment('<%= current_user.name %>', '<%= @pin.id %>', body)" class="comment-form center">
    <h3>Speak your mind</h3>
    <div class="form-group center">
      <textarea class="form-control pic-comment" rows="5" placeholder="What?" ng-model="body"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Comment</button>
  </form>
</div> <!-- .panel -->
<% javascript_include_tag "comments/application" %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default cp-font" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed cp-font" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Cigar Pics", root_path, class: "navbar-brand cp-font" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse cp-font">
      <ul class="nav navbar-nav navbar-right">
	<li><%= link_to 'Home', root_path %></li>
	<li><%= link_to 'About', about_path %></li>
	<li><%= link_to '+ Add Cigar', new_pin_path %></li>
	<% if user_signed_in? %>
	  <li><%= link_to 'Settings', edit_user_registration_path %></li>
	  <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
	<% else %>
	  <li><%= link_to 'Log in', new_user_session_path %></li>
	  <li><%= link_to 'Sign up', new_user_registration_path %></li>
	<% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cigar Pics</title>
	<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <%= render 'layouts/header' %>
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>
    <%= yield %>
</body>
</html>

app/views/pages/_home.html.erb
<div class="login center">
  <h1>What Are You Smoking?</h1>
    <% if user_signed_in? %> 
      <br>
      <%= link_to "View cigar", pins_path, class: "btn btn-default btn-lg" %>
      <%= link_to "Add cigar", new_pin_path, class: "btn btn-primary btn-lg" %>
    <% else %> 
      <br>
      <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
      <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
    <% end %>
</div>

app/views/pages/about.html.erb
<div class="jumbotron center">
<h1>About Cigar Pics</h1>
  <div class="container">
    <%= link_to image_tag("Cigar_Stash.JPG", width: "250", height: "200"), "https://github.com/mkjenkins101" %>
    <p>Cigar Pics creates an affinity for cigars and <br> 
    develops a brotherhood among cigar lovers new and great.<br>
    Grow and cultivate your appreciation for cigars and find<br>
    all the information you need from which sticks to try,<br>
    how to enjoy them properly, what to pair them with, and<br>
    detailed reviews by your fellow cigar lovers. Enjoy!</p>
  </div>
</div>

app/views/pages/home.html.erb
<div class="jumbotron center">
  <h1>Mitch's Pin Picks</h1>
    <p>This is the beginning!
    <% if user_signed_in? %> 
      <br>
      <%= link_to "View pins", pins_path, class: "btn btn-default btn-lg" %>
      <%= link_to "Add pin", new_pin_path, class: "btn btn-primary btn-lg" %>
    <% else %> 
      <br>
      <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
      <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
    <% end %>
    </p>
</div>

app/views/pins/_form.html.erb
<div class="panel">
  <%= form_for @pin, html: { multipart: true } do |f| %>
    <% if @pin.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

        <ul>
        <% @pin.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :image %>
      <%= f.file_field :image, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_field :description, class: "form-control" %>
    </div>
		<div class="form-group">
      <%= f.label :shape %>
			<%= f.select :shape, options_for_select(Pin.cigar_shape), {}, class: "form-control" %>
    </div>
    <div class="form-group size-fields">
      <%= f.label :length %>
			<%= f.select :length, options_for_select(Pin.cigar_length), {}, class: "form-control" %>
    </div>
    <div class="form-group size-fields">X</div>
    <div class="form-group size-fields">
      <%= f.label :ring %>
			<%= f.select :ring, options_for_select(Pin.cigar_ring), {}, class: "form-control" %>
    </div>
		<div class="form-group">
      <%= f.label :wrapper %>
			<%= f.select :wrapper, options_for_select(Pin.cigar_wrapper), {}, class: "form-control" %>
    </div>
    <div class="form-group actions">
      <%= f.submit class: "btn btn-primary btn-sm" %>
    </div>
  <% end %>
</div>

app/views/pins/_ratings.html.erb
<% if current_user %>
  <% if overall == 0 %>
    Construction: <%= rating_for @pin, "construction", disable_after_rate: false, star: 10 %>
    Burn: <%= rating_for @pin, "burn", disable_after_rate: false, star: 10 %>
    Flavor: <%= rating_for @pin, "flavor", disable_after_rate: false, star: 10 %>
  <% else current_user %>
    Construction: <%= rating_for @pin, "construction", disable_after_rate: false, star: 10 %>
    Burn: <%= rating_for @pin, "burn", disable_after_rate: false, star: 10 %>
    Flavor: <%= rating_for @pin, "flavor", disable_after_rate: false, star: 10 %>
    Overall: <%= rating_for @pin, "overall", disable_after_rate: true, star: overall, avg: 10 %>
  <% end %>
<% end %>

app/views/pins/edit.html.erb
<div class="panel panel-main">
  <div class="panel-heading">
    <h1>Editing Cigar Pic</h1>
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>

  <div class="panel-footer">
    <%= link_to 'Show', @pin %> |
    <%= link_to 'All Pics', pins_path %>
  </div>
</div>

app/views/pins/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>
<div id="pins" class="transistions-enabled">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(pin.image.url(:medium)), pin %>
      <div class"panel-body">
	  <%= pin.description %></br>
	  <strong><%= pin.user.try(:name) %></strong>
          <% if pin.user == current_user %>
	    <div class="actions">
              <%= link_to edit_pin_path(pin) do %>
	        <span class="glyphicon glyphicon-edit">Edit</span>
	      <% end %>
              <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
	        <span class="glyphicon glyphicon-trash">Delete</span>
	      <% end %>
            </div>
          <% end %>
      </div>
    </div>
  <% end %>
</div>
<div class="center">
  <% will_paginate @pins %>
  <%= will_paginate @pins, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/new.html.erb
<div class="panel panel-main cp-font">
  <div class="panel-heading center">
    <h1>New Cigar Pic</h1>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
  <div class="panel-footer">
    <%= link_to 'All Pics', pins_path %>
  </div>
</div>

app/views/pins/show.html.erb
<div class="panel panel-main">
  <div class="panel-header">
		<%= button_to 'All Pics', pins_path, method: 'get', class: "btn btn-secondary btn-sm btn-main" %>
    <% if @pin.user == current_user %>
			<%= button_to 'Edit', edit_pin_path, method: 'get', class: "btn btn-secondary btn-sm btn-edit" %>
    <% end %>
		<%= button_to 'Pick Pic', "", class: "btn btn-primary btn-sm btn-pick-pic" %>
	</div>
  <div class="panel-body">
		<div class="pin-content">
    	<%= image_tag @pin.image.url(:medium) %><br>
			<% if @pin.user != current_user %>
      	<p><%= @pin.user.name %></p>
			<% end %>
		</div> <!-- .pin-content -->
  </div> <!-- .panel-body -->
	<div class="pin-description">
  	<strong><%= @pin.description %></strong>
	</div>
	<div class="ratings center">
  	<div class="small-2 large-4 columns">
    	<%= render 'pins/ratings' %>
  	</div>
	</div> <!-- .ratings -->
	<div class="cigar-specs cp-font">
		<div class="cigar-spec">
		<strong>Shape: </strong><%= @pin.shape %>
		</div>
		<div class="cigar-spec">
		<strong>Size: </strong><%= @pin.length %> X <%= @pin.ring %>
		</div>
		<div class="cigar-spec">
		<strong>Wrapper: </strong><%= @pin.wrapper %>
		</div>
	</div><!-- .cigar-specs -->
</div> <!-- .panel -->
<% if current_user != nil %> 
	<%= render 'comments/index' %>
<% end %>